import { ApiProperty } from '@nestjs/swagger';

/**
 * DTO for category performance data
 */
export class CategoryPerformanceItemDto {
  @ApiProperty({
    description: 'Category ID',
    example: '550e8400-e29b-41d4-a716-446655440001',
  })
  categoryId: string;

  @ApiProperty({
    description: 'Category name',
    example: 'Outerwear',
  })
  categoryName: string;

  @ApiProperty({
    description: 'Total units sold in this category',
    example: 125,
  })
  unitsSold: number;

  @ApiProperty({
    description: 'Total revenue generated by this category',
    example: 12500.75,
  })
  revenue: number;

  @ApiProperty({
    description: 'Percentage of total sales',
    example: 35.5,
  })
  percentage: number;

  @ApiProperty({
    description: 'Growth rate compared to previous period',
    example: 12.5,
  })
  growthRate: number;
}

/**
 * DTO for category performance trend data
 */
export class CategoryPerformanceTrendDto {
  @ApiProperty({
    description: 'The time period (date)',
    example: '2025-01-15',
  })
  date: string;

  @ApiProperty({
    description: 'Category ID',
    example: '550e8400-e29b-41d4-a716-446655440001',
  })
  categoryId: string;

  @ApiProperty({
    description: 'Category name',
    example: 'Outerwear',
  })
  categoryName: string;

  @ApiProperty({
    description: 'Revenue for this category in this period',
    example: 2500.50,
  })
  revenue: number;
}

/**
 * DTO for complete category performance analytics response
 */
export class CategoryPerformanceResponseDto {
  @ApiProperty({
    description: 'Total revenue across all categories',
    example: 125000.50,
  })
  totalRevenue: number;

  @ApiProperty({
    description: 'Number of active categories',
    example: 8,
  })
  activeCategories: number;

  @ApiProperty({
    description: 'Top performing category',
    example: 'Outerwear',
  })
  topCategory: string;

  @ApiProperty({
    description: 'Performance data for individual categories',
    type: [CategoryPerformanceItemDto],
  })
  categoryPerformance: CategoryPerformanceItemDto[];

  @ApiProperty({
    description: 'Category performance trends over time',
    type: [CategoryPerformanceTrendDto],
  })
  performanceTrends: CategoryPerformanceTrendDto[];

  @ApiProperty({
    description: 'Date range for the analytics',
    example: {
      startDate: '2025-01-01T00:00:00.000Z',
      endDate: '2025-01-31T23:59:59.999Z',
    },
  })
  dateRange: {
    startDate: Date;
    endDate: Date;
  };
}

/**
 * DTO for category performance error response
 */
export class CategoryPerformanceErrorResponseDto {
  @ApiProperty({
    description: 'Error message',
    example: 'Failed to retrieve category performance metrics',
  })
  error: string;

  @ApiProperty({
    description: 'Detailed error message',
    example: 'Database connection error',
  })
  message: string;

  @ApiProperty({
    description: 'Date range that was requested',
    example: {
      startDate: '2025-01-01T00:00:00.000Z',
      endDate: '2025-01-31T23:59:59.999Z',
    },
  })
  dateRange?: {
    startDate: Date;
    endDate: Date;
  };
}
