import { ApiProperty } from '@nestjs/swagger';

/**
 * DTO for sales data by time period
 */
export class SalesByTimePeriodDto {
  @ApiProperty({
    description: 'The time period (date)',
    example: '2025-01-15',
  })
  date: string;

  @ApiProperty({
    description: 'Total revenue for the period',
    example: 12500.75,
  })
  revenue: number;

  @ApiProperty({
    description: 'Number of orders for the period',
    example: 125,
  })
  orders: number;

  @ApiProperty({
    description: 'Average order value',
    example: 100.01,
  })
  averageOrderValue: number;
}

/**
 * DTO for top product sales data
 */
export class TopProductDto {
  @ApiProperty({
    description: 'Product ID',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  productId: string;

  @ApiProperty({
    description: 'Product name',
    example: 'Premium Leather Jacket',
  })
  productName: string;

  @ApiProperty({
    description: 'Number of units sold',
    example: 42,
  })
  unitsSold: number;

  @ApiProperty({
    description: 'Total revenue generated by this product',
    example: 4199.99,
  })
  revenue: number;
}

/**
 * DTO for sales by category data
 */
export class SalesByCategoryDto {
  @ApiProperty({
    description: 'Category ID',
    example: '550e8400-e29b-41d4-a716-446655440001',
  })
  categoryId: string;

  @ApiProperty({
    description: 'Category name',
    example: 'Outerwear',
  })
  categoryName: string;

  @ApiProperty({
    description: 'Total revenue for this category',
    example: 8750.50,
  })
  revenue: number;

  @ApiProperty({
    description: 'Percentage of total sales',
    example: 35.5,
  })
  percentage: number;
}

/**
 * DTO for complete sales analytics response
 */
export class SalesAnalyticsResponseDto {
  @ApiProperty({
    description: 'Total revenue for the period',
    example: 25000.75,
  })
  totalRevenue: number;

  @ApiProperty({
    description: 'Total number of orders for the period',
    example: 250,
  })
  totalOrders: number;

  @ApiProperty({
    description: 'Average order value',
    example: 100.00,
  })
  averageOrderValue: number;

  @ApiProperty({
    description: 'Sales growth percentage compared to previous period',
    example: 12.5,
  })
  salesGrowth: number;

  @ApiProperty({
    description: 'Sales data broken down by time period',
    type: [SalesByTimePeriodDto],
  })
  salesByTimePeriod: SalesByTimePeriodDto[];

  @ApiProperty({
    description: 'Top selling products',
    type: [TopProductDto],
  })
  topProducts: TopProductDto[];

  @ApiProperty({
    description: 'Sales breakdown by category',
    type: [SalesByCategoryDto],
  })
  salesByCategory: SalesByCategoryDto[];

  @ApiProperty({
    description: 'Date range for the analytics',
    example: {
      startDate: '2025-01-01T00:00:00.000Z',
      endDate: '2025-01-31T23:59:59.999Z',
    },
  })
  dateRange: {
    startDate: Date;
    endDate: Date;
  };
}

/**
 * DTO for error response
 */
export class ErrorResponseDto {
  @ApiProperty({
    description: 'Error message',
    example: 'Failed to retrieve sales analytics',
  })
  error: string;

  @ApiProperty({
    description: 'Detailed error message',
    example: 'Database connection error',
  })
  message: string;

  @ApiProperty({
    description: 'Date range that was requested',
    example: {
      startDate: '2025-01-01T00:00:00.000Z',
      endDate: '2025-01-31T23:59:59.999Z',
    },
  })
  dateRange?: {
    startDate: Date;
    endDate: Date;
  };
}
